const types = {
  REQUEST_CHANNELS: 'REQUEST_CHANNELS',
  RECEIVE_CHANNELS: 'RECEIVE_CHANNELS',
  ERROR_CHANNELS: 'ERROR_CHANNELS',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_ONLINE: 'SHOW_ONLINE',
  SHOW_OFFLINE: 'SHOW_OFFLINE',
  REMOVE_CHANNEL: 'REMOVE_CHANNEL',
  ADD_CHANNEL: 'ADD_CHANNEL'
};

export default types;
