const types = {
  REQUEST_STREAMS: 'REQUEST_STREAMS',
  RECEIVE_STREAMS: 'RECEIVE_STREAMS',
  ERROR_STREAMS: 'ERROR_STREAMS',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_ONLINE: 'SHOW_ONLINE',
  SHOW_OFFLINE: 'SHOW_OFFLINE',
  REMOVE_STREAM: 'REMOVE_STREAM',
  ADD_STREAM: 'ADD_STREAM'
};

export default types;
